= Balisage pre-conference symposium program announced

The balisage pre-conference symposium, XML In, Web Out: International Symposium on sub rosa XML, has finally taken http://balisage.net/XML-In-Web-Out/symposiumProgram.html[shape] and (along with the http://balisage.net/index.html[full conference]) it looks to be a good one.


Having read the papers I can give a little of the flavor of what to expect.


=== Welcome 
===== Jim Fuller, Marklogic

Where yours trully offers observations on the themes comprising the day's talks briefly touching upon real world, non-trivial examples of the XML stack working hand in hand with other modern technology stacks.  


=== XSLT as a powerful static website generator: Hogrefe's Clinical Handbook of Psychotropic Drugs 
===== Martin Kraetke & Gerrit Imsieke, le-tex publishing services GmbH

This paper reminds me of a quote often said at http://www.marklogic.com[work], something to the effect of:

> Every company has a publishing problem.

Often there is high value XML waiting to be leveraged in every company. Even publishing companies can benefit from reusing single source XML originally created for print to derive rich web and mobile applications. 

XSLT is a wonderful technology with a very poor image problem ... mostly because XSLT 1.0 was 'slow walked' in the browser. Most developers wrongly think XSLT 1.0 (in the browser) is the definition of XSLT ... nothing could be further from the truth. 

This paper does a great job at showing how simple it is to easily transform XML content with XSLT 2.0 generating cache friendly, standalone (offline viewable) static websites.

As a bonus, the actual application is pretty interesting as well!


=== The XML expert’s path to web applications 
===== Anne Brüggemann-Klein, Technical University of Munich (TUM)




=== Meta(data)morphosis 
===== Ashley M. Clark, Sarah Connell, Northeastern University




=== Messaging format persistence in Healthcare.gov and other large enterprise systems 
===== Damon Feldman, MarkLogic Corporation




=== XQuery Is Not (Just) a Query Language 
===== Gregory Murray, Princeton Theological Seminary





=== The Kiln XML Publishing Framework 
===== Paul Caton & Miguel Vieira, King's College, London





=== Panel Discussion: Multi Stack Harmony

The Symposium presentations demonstrate how the XML stack can work in harmony with other common stacks (web, java, etc), playing to each others strengths while offsetting weaknesses. A panel comprised of speakers and domain experts will discuss techniques that promote harmony and interworking between technology stacks, as well as idioms to be avoided. Questions and observations from attendees will shape the discussion of how to make the XML stack 'play nice' with others.


http://www.balisage.net/XML-In-Web-Out/index.html

