= The Good, Bad and Ugly Success of XProc v1

Some http://www.xmlprague.cz#[XML Prague] inspired observations of XProc v1. 

XProc is a W3C standard that defines an XML Pipeline language.

_An XML Pipeline specifies a sequence of operations to be performed on zero or more XML documents. Pipelines generally accept zero or more XML documents as input and produce zero or more XML documents as output. Pipelines are made up of simple steps which perform atomic operations on XML documents and constructs similar to conditionals, iteration, and exception handlers which control which steps are executed._

The original goal for XProc v1 was to be able to manage processing pipelines of XML documents. 

== The Good

XProc v1 got most of the hard parts of specifying pipelines stunningly correct going far beyond modeling simple workflows defining a full blown dataflow language.

The WG careful work on XProc v1 means that the current semantics and model are a  solid foundation, sufficiently abstracted and generalised to handle the most complex pipelines.


=== Sophisticated pipelines 

=== Small but dedicated core community 

=== Money
 Gerrit mention of '7 figure sums' on the back of XProc technology

=== Dynamic

The XML Syntax provides a highly flexible 

=== Implementations

XMLCalabash 


== The Bad

https://www.w3.org/TR/xproc-v2-req/[XProc v2 requirements] is a good list of what needed to be fixed with XProc.


=== MUST requirements

The *MUST* being:

==== Simplify parameters

Parameters were too complex

==== Integrate non-XML documents into pipelines

In many use cases and workflows we want to flow through heterogenous data and documents.

==== Align with XPath 3.0 technologies

Adopting the goodness of XPath 3.0 brings functional programming parity to XProc.

==== Add explicit flow handling

Flows are implicitly determined by port connections ... this is too subtle.

==== Allow arbitrary XDM values in variables

Options and variables just containing strings turns out to be far too limiting

==== Allow attribute value templates

Not being able to use AVT makes for some complicated pipelines

==== Support a variety of syntactic simplifications

Any version 1 of a language comes with burrs to be smooted over

=== SHOULD requirements

And *SHOULD*:

==== Associate arbitrary metadata with documents

Every document has metadata

==== Support steps with a dynamic number of ports

Implicit port connection makes this hard

==== Provide improved status information

Comprehending flow 

Debugging

==== Provide a mechanism for importing user-defined functions

Letting XQuery or XSLT functions be loaded into scope 

==== Consider using XDM everywhere

==== Simplify p:viewport and allow it to have multiple outputs


== The Ugly

There are some aspects of XProc v1 which are 'deal breakers' for many developers.

==== Angle brackets

The XML Syntax means for many developers means XProc will never even be considered.


==== Steep learning curve

Other XML communities have looked into using XProc and failed
 


== The Relevant 

_'If you don’t like change, you’re going to like irrelevance even less'_


Is a meme that caught my eye last week. Its apropos to XProc in that 

https://xproc.github.io/specification/[XProc draft v2] attempted to fix 'The Bad' without addressing 'The Ugly'?

Speaking for myself (and not the Working Group) I would like XProc to appeal to:

* publishing stacks
* web stacks 
* casual (command line scripting)

* XSLT/XQuery users
* Data science (people using R, julia, python)
* my grandmother

I 