= Balisage pre-conference symposium program announced

The balisage pre-conference symposium, XML In, Web Out: International Symposium on sub rosa XML, has finally taken http://balisage.net/XML-In-Web-Out/symposiumProgram.html[shape] and (along with the http://balisage.net/index.html[full conference]) it looks to be a good one.


Having read the papers I can give a little of the flavor of what to expect.


=== Welcome 
===== Jim Fuller, Marklogic

Where yours trully offers observations on the themes comprising the day's talks briefly touching upon real world, non-trivial examples of the XML stack working hand in hand with other modern technology stacks.  


=== XSLT as a powerful static website generator: Hogrefe's Clinical Handbook of Psychotropic Drugs 
===== Martin Kraetke & Gerrit Imsieke, le-tex publishing services GmbH

This paper reminds me of a quote often repeated at http://www.marklogic.com[work], something to the effect of:

> Every company has a publishing problem.

High value XML should be leveraged by every company to help solve their publishing problems. Even publishing companies can benefit from reusing single source XML originally created for print to derive rich web and mobile applications. 

Like much of the XML stack, XSLT is a wonderful technology with a very poor image problem ... mostly because XSLT 1.0 was 'slow walked' in the browser. 

Most developers formed an opinion on XSLT based on XSLT 1.0 in the browser. I think part of the reason why we do not see as much usage of XSLT to generate static applications is that developers were trying to 'shoe horn' using XSLT 1.0 (in a browser) for the job. There are better ways to do that kind of thing in the browser now (http://www.saxonica.com/ce/index.xml[saxon-ce] comes to mind) but stepping back, XSLT processing in the browser is a distraction ... we have full blooded tools for doing the job right.  

This paper shows how simple it is to easily transform XML content with XSLT 2.0 generating cache friendly, standalone (offline viewable) static websites.

As a bonus, the actual static application is pretty interesting as well!


=== The XML expert’s path to web applications 
===== Anne Brüggemann-Klein, Technical University of Munich (TUM)

This paper is a good illustration of how  the XML stack can underpin a thin-client https://en.wikipedia.org/wiki/XRX_(web_application_architecture)[XRX] web application.

* OO domain driven design
* event driven (with statecharts)
* https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller[MVC]
* observer pattern and server push with multi-client Web applications 

With hard won advice provided along the way.

=== Meta(data)morphosis 
===== Ashley M. Clark, Sarah Connell, Northeastern University




=== Messaging format persistence in Healthcare.gov and other large enterprise systems 
===== Damon Feldman, MarkLogic Corporation




=== XQuery Is Not (Just) a Query Language 
===== Gregory Murray, Princeton Theological Seminary





=== The Kiln XML Publishing Framework 
===== Paul Caton & Miguel Vieira, King's College, London





=== Panel Discussion: Multi Stack Harmony

The Symposium presentations demonstrate how the XML stack can work in harmony with other common stacks (web, java, etc), playing to each others strengths while offsetting weaknesses. A panel comprised of speakers and domain experts will discuss techniques that promote harmony and interworking between technology stacks, as well as idioms to be avoided. Questions and observations from attendees will shape the discussion of how to make the XML stack 'play nice' with others.


http://www.balisage.net/XML-In-Web-Out/index.html

