= Not your Father's XQuery


XQuery 1.0
https://www.w3.org/TR/xquery/


XQuery 3.0
https://www.w3.org/TR/xquery-30/



group by clause in FLWOR Expressions (3.10.7 Group By Clause).
tumbling window and sliding window in FLWOR Expressions (3.10.4 Window Clause).
count clause in FLWOR Expressions (3.10.6 Count Clause).
allowing empty in 3.10.2 For Clause, for functionality similar to outer joins in SQL.
try/catch expressions (3.15 Try/Catch Expressions).
Dynamic function call (3.2.2 Dynamic Function Call ).
Inline function expressions (3.1.7 Inline Function Expressions).
Private functions (4.18 Function Declaration).
Switch expressions (3.13 Switch Expression).
Computed namespace constructors (3.9.3.7 Computed Namespace Constructors).
Output declarations (2.2.4 Serialization).
Annotations (4.15 Annotations).
Function assertions in function tests.
A string concatenation operator (3.6 String Concatenation Expressions).
A mapping operator (3.17 Simple map operator (!)).




XQuery 3.1
https://www.w3.org/TR/xquery-31/