= Balisage pre-conference symposium program announced

The balisage pre-conference symposium, XML In, Web Out: International Symposium on sub rosa XML, has finally taken http://balisage.net/XML-In-Web-Out/symposiumProgram.html[shape] and (along with the http://balisage.net/index.html[full conference]) it looks to be a good one.


Having read the papers I can give a little of the flavor of what to expect.


=== Welcome 
===== Jim Fuller, Marklogic

Where yours truly offers observations on the themes comprising the day's talks briefly touching upon real world, non-trivial examples of the XML stack working hand in hand with other modern technology stacks.  


=== XSLT as a powerful static website generator: Hogrefe's Clinical Handbook of Psychotropic Drugs 
===== Martin Kraetke & Gerrit Imsieke, le-tex publishing services GmbH

This paper reminds me of a quote often repeated at http://www.marklogic.com[work], something to the effect of:

> Every company has a publishing problem.

High value XML should be leveraged by every company to help solve their publishing problems. Even publishing companies can benefit from reusing single source XML originally created for print to derive rich web and mobile applications. 

Like much of the XML stack, XSLT is a wonderful technology with a very poor image problem ... mostly because XSLT 1.0 was 'slow walked' in the browser. 

Most developers formed an opinion on XSLT based on XSLT 1.0 in the browser. I think part of the reason why we do not see as much usage of XSLT to generate static applications is that developers were trying to 'shoe horn' using XSLT 1.0 (in a browser) for the job. There are better ways to do that kind of thing in the browser now (http://www.saxonica.com/ce/index.xml[saxon-ce] comes to mind) but stepping back, XSLT processing in the browser is a distraction ... we have full blooded tools for doing the job right without the need to involve a browser.  

This paper shows how simple it is to easily transform XML content with XSLT 2.0 generating cache friendly, standalone (offline viewable) static websites.

As a bonus, the actual static application is pretty interesting as well!


=== The XML expert’s path to web applications 
===== Anne Brüggemann-Klein, Technical University of Munich (TUM)

This paper is a good illustration of how  the XML stack can underpin a thin-client https://en.wikipedia.org/wiki/XRX_(web_application_architecture)[XRX] web application.

* OO domain driven design
* event driven (with statecharts)
* https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller[MVC]
* observer pattern and server push with multi-client Web applications 

With hard won advice provided along the way.


=== Meta(data)morphosis 
===== Ashley M. Clark, Sarah Connell, Northeastern University

This paper nails the symposium topic squarely illustrating how the XML stack is highly capable in handling all the mess that comes with 'metamorphosis of a 'real world' corpus (warts and all) intended for web publication. 

I used to say if I were marooned on a desert island I would take Perl with me (or lisp) ... nowadays it would be the XML stack as it gives me a lot of practical (escape) routes for working with real problems. 

Furthermoree the authors show how the XML Stack + web stack du jour (no passive aggro intended ...) work together.


=== Messaging format persistence in Healthcare.gov and other large enterprise systems 
===== Damon Feldman, MarkLogic Corporation

Large systems come with more problems due to expanded scope. Need to integrate with a few databases ... in the hyper enterprise make that 50 or 100 databases. Need to respond to searches in milliseconds, in the hyper enterprise do that with a few 100k people at the same time ... and so forth and so on .... 

It is not just that problems are 'super sized' it is also true that new complexity arises from integrating already complex systems.

The author provides deep insight on how simplifying design and modelling decisions aided by the XML stack helps with solving the hardest problems in our industry today. 

Most will have heard from the news of the challenges of healthcare.gov, though many will not know how the XML Stack working alongside other technologies helped solve those challenges under the harshest operating conditions.


=== XQuery Is Not (Just) a Query Language 
===== Gregory Murray, Princeton Theological Seminary

The author provides excellent advice on using modern XQuery as a fully mature functional programming language.

* enabling MVC architecture
* ensuring functions are testable
* using RESTXQ for URL rewriting
* isolating implementation-specific functions into separate modules

XQuery hits a sweet spot and a highly productive language - something near and dear to my heart and I think many will find the author's talk full of great advice and tips for working with modern XQuery. 


=== The Kiln XML Publishing Framework 
===== Paul Caton & Miguel Vieira, King's College, London

The last talk of the day demonstrates how the XML Stack provides a highly flexible foundation for provisioning a broad variety of web applications, using different sources enabling complex features such as:

* search
* pdf/epub format 
* RDF (with https://projects.eclipse.org/projects/technology.rdf4j[Sesame])

all possible via non technical administrative interfaces.

=== Panel Discussion: Multi Stack Harmony

TBD

=== Register to attend now

If any of this sounds interesting I urge you to register now.

http://www.balisage.net/XML-In-Web-Out/index.html

