= Not your Father's XQuery

Last year, I embarrassed myself slightly by losing a little patience with someone who I believed was blindly slagging off XSLT. 

What the unnamed individual did not realise was that they were talking about an ancient version of https://www.w3.org/TR/xslt[XSLT]. We can partially blame browser built in support of v1.0 (almost to the point where I think we should lobby for XSLT 1.0 removal from all browsers!). 

Even with the existance of the excellent http://www.saxonica.com/ce/index.xml[SAXON-CE XSLT v2.0] implementation for the browser, its hard to get folks to take another look at XSLT in browser context (that won't stop me from using it!). If javascript v1.0 was still used in the browser I doubt it would enjoy the broad acceptance it has today.

I've not been as charitable with younger programmers as older programmers were with me when I was first learning the trade. The rate of change in our industry is ridiculous and expecting newcomers to have all the context about any particular programming language is quite impossible. Clearly the onus is upon those with 'context' to communicate what a programming language is today.

XQuery is undergoing a similar situation where developers form an opinion of XQuery based on v1.0 of the language. 

To feel like you are travelling back in time (or to another universe) just take a look at how xquery gets used in any of http://www.oracle.com/technetwork/database-features/xmldb/index-087544.html[Oracle] or http://beyondrelational.com/modules/2/blogs/28/posts/10279/xquery-labs-a-collection-of-xquery-sample-scripts.aspx[Microsoft's] database offerings. When I look at XQuery examples in those environments my eyes get blurry and I feel light headed.

What is even more interesting is that there has been recent work in XQuery, for example there are some XQuery 3.0 functionality listed in Oracle documentation for https://docs.oracle.com/cd/E49465_01/doc.23/e49333/oxh.htm#BDCUG541['Oracle XQuery for Hadoop']. How a developer could ever find this out without digging (as I did) I do not know.  

To summarise, anyone using XQuery in those environments would conclude XQuery is:

* only for querying XML
* an unweildy addon to much simpler SQL
* not an elegant programming language
* stale eg. developed in the previous decade

As a daily user of modern XQuery, the most exciting and defining characteristics of XQuery are what has happened over the past couple of years. We should try to clarify what XQuery is today.

The newer XQuery specs do a surprisingly clear job at listing out 'whats new'.

* https://www.w3.org/TR/xquery-30/[XQuery 3.0 Specification]

* https://www.w3.org/TR/xquery-31/[XQuery 3.1 Specification ]

And there have been many good presentations:





=== What is XQuery today ?

I will reproduce the current https://en.wikipedia.org/wiki/XQuery[Wikipedia definition of XQuery]:

_XQuery is a query and functional programming language that queries and transforms collections of structured and unstructured data, usually in the form of XML, text and with vendor-specific extensions for other data formats (JSON, binary, etc.)._

Even this definition is a bit out of date, as the latest specification (https://www.w3.org/TR/xquery-31/[XQuery v3.1]) which is a W3C Candidate Recommendation adds https://www.w3.org/TR/2015/CR-xquery-31-20151217/#id-maps[maps], https://www.w3.org/TR/2015/CR-xquery-31-20151217/#id-arrays[arrays] and https://www.w3.org/TR/2015/CR-xquery-31-20151217/#id-string-constructors[string constructors] to the language making it very easy to work with other formats like JSON.  

So what does modern XQuery look like ?

```
```



===  What is XQuery 1.0 ?

The spec circa 2010
https://www.w3.org/TR/xquery/


=== What is XQuery 1.1 ?



=== What is XQuery 2.0 ?

The WG decided to skip this version number to align to XSLT v3.0.


=== What is XQuery 3.0 ?

circa 2014
https://www.w3.org/TR/xquery-30/


==== Ease of use

Some of the new features like:

* try/catch 
* string concat with ||
* mapping operator ! for simple for expressions
* count clause in FLWOR Expressions
* Switch expressions
* Computed namespace constructors
* Output declarations

are aimed at making the language easier formalising many common extensions found in the wild.

==== Selection

group by clause in FLWOR Expressions (3.10.7 Group By Clause).
tumbling window and sliding window in FLWOR Expressions (3.10.4 Window Clause).

==== Functions, functions, functions

let $sq :=
 function($i as xs:integer) as xs:integer {
 $i * $i
 }
Inline functions are expressions and can
appear anywhere an expression is allowed.

Function literals:
– fn:abs#1, fn:max#2, my:func#3
● Partial application (currying):
– string-join(?, ', ')
– contains(?, ?, 'http://collation/case-blind')
● Run-time discovery:
– function-lookup($name, $arity)

Functions that take functions
as an argument
● fn:filter($function, $sequence)
● fn:map($function, $sequence)
● fn:map-pairs($function, $seq1, $seq2)
● fn:fold-left($function, $initial, $sequence)
● fn:fold-right($function, $initial, $sequence)

Properties of functions
● function-name($function)
● function-arity($function)

Use cases for higher-order
functions
● Dynamic despatch mechanism
– alternative to XSLT template rules
– substitute for polymorphism
● Overcome limitations of XDM type system
● Reusable algorithms such as detection of
cycles in a graph
● Reduce the need to write simple things
using recursion


==== Annotations

==== The Rest

Other new functions
* trig/math functions: sin(), cos(), sqrt() etc
* analyze-string()
* format-date(), format-number(), generateid(),
unparsed-text() etc
– moved from XSLT to common library
* head(), tail(), path()
* environment-variable(), uri-collection()
* parse(), serialize()
* Function assertions in function tests.




=== What is XQuery 3.1 ?

circa 2016

https://www.w3.org/TR/xquery-31/

==== maps

==== arrays

==== string constructors

==== The Rest

are being proposed to be added to the language

