= test1

This post is definately under the category of 'distraction'. For the past few years we have all witnessed the slosh of events, rise of (honest populism)[http://www.nationalreview.com/corner/392577/jeff-sessions-elites-have-had-their-day-joel-gehrke] and validation that we live in a world with alternate competing realities.

For people who identify themselves as progressives the world became a richer, safer, happier, more peaceful place ... all analysis verifies this. 

This truth however is not well distributed eg. there are 

== Trying to make sense of how we got here

Understanding where we are is a function of where we have been 

When nobles could use money to hire proxies to fight for them
http://www.lordsandladies.org/decline-of-feudalism.htm

seperation of church and state
https://en.wikipedia.org/wiki/John_Locke

=== Revolution

=== Civil War

=== WWI 

=== WWII

=== one or two parties ?

Globalism

This potted history seems plausible only because I choose data points from which to draw a line of reasoning.

Events in history are not linear or contiguous but fully asynchronous with each of the following ideas having examples all the way back into antiquity.

Such ideas commonly live on in stagnate pools, resevoirs of the disenfranchised or as oddities of culture.

== The American dream today

Easy Rider is a prophetic film
https://en.wikipedia.org/wiki/Easy_Rider

But it is also baleful and lightweight in that it claims to show hard truths when actually all that is revealed is the same story of human nature in the guise of riding motorcycles. The refrain of 'America was better before' echos the 'Make America great again' tripe ... in most instances I think sentimentality calcifies the brains of older folk who wish for times when they simply were younger (more supple, flexible, handsome, vital ...). 

Bannon's apocalyptic views have some threads of truth in that America is governed by a closed class of people, with only their own interests at heart he is perfectly naive in thinking that this is any different from what has happened with every flavour of governement throughout all of humanity. Even more childlike is the view that his views will resolve that most basic of human tendencies. If anything governments that distract the ruling class and still allow 

The American dream was always that first immigrant wave, be it Irish fleeing persacution or the vietnamese running away from war.

The dream ebbs with every generation and turns into resentment after the third or fourth generation.

Maybe eventually (classic technocrat speaking ...) we will just plug those people into a virtual reality where they are installed as ruler of planets, solar systems and galaxies ... to live their entire lives subjugating virtual subjects.

== Where it goes from here

The old notion of what comprises a nation state is changing.

Global capitalism, the internet and individual (regardless of class) freedom of movement has rendered the notion of contiguous defendeable borders gone.

This becomes a sort of 'club or country'(football reference) type argument for some people who feel their identify diminished.


The rise of the machines has been in motion for hundreds of years disrupting employment for hundreds of millions, creating a new kind of under class. This is only going to get worst in terms of negative impact on groups unable to change.

We no longer talk about all the lost jobs

The alternate theory is that this is the last gasp from a generation of people who past their primes are finally getting listened too and pushing all the buttons to remain in power before entering the final winter of their lives.

== It will get worst before it gets better

What is certain is that the current clash of ideas will make things worst in terms of normal analysis.

== The real solution


The natural baffles of time, distance, culture, nations and overall disconnectedness have fallen away.

All of us are effected by all of us and vice versa, ad infinitum.

This was always the truth, it is just the time component that has changed.


The long term is a planet scale solution ... so far Facebook looks more likely then any political system
