= Distracted, confused and definately not about XQuery

This post is firmly under the category of 'distraction'. 

For the past few years we have witnessed the slosh of events, rise of (honest populism)[http://www.nationalreview.com/corner/392577/jeff-sessions-elites-have-had-their-day-joel-gehrke] and validation that we live in a world with alternate, competing realities.

I find writing about such things helps synthesize the world for me. It is indulgent, unrigorous and speculative ... but I offer it up to the interwebs if not just to record my mental state circa early 2017.

For people who identify themselves as progressives the world has become a richer, safer, happier, more peaceful place ... all analysis verifies this. Walls were torn down, armies stood down, and freedoms increased for people previously denied them. The profit of peace however are far from evenly applied nor are they synchronous. For some bubbles of society they are worst off stating averages just annoys them.

We have also had wars, freedoms denied and a deterioration 

Being a technocrat my immediate instinct is how to solve the problem. This approach is seductive to liberals and rationals who view the world as a series of puzzles to solve.

== Trying to make sense of how we got here

Understanding where we are is a function of where we have been.

When nobles could use money to hire proxies to fight for them
http://www.lordsandladies.org/decline-of-feudalism.htm

seperation of church and state
https://en.wikipedia.org/wiki/John_Locke


=== WWI 

=== WWII

=== one or two parties ?

Globalism

This potted history seems plausible only because I have choosen the data points from which to draw a coherent line of reasoning.

Events in history are not linear or contiguous but fully asynchronous with each of the following ideas having examples all the way back into antiquity.

Such ideas commonly live on in stagnate pools, within resevoirs of the disenfranchised or in the weirder edge of culture.

== American dream

Easy Rider is a prophetic film
https://en.wikipedia.org/wiki/Easy_Rider

== Where it goes from here

The old notion of what comprises a nation state is changing.

Global capitalism, the internet and individual (regardless of class) freedom of movement has rendered the notion of contiguous defendeable borders gone.

This becomes a sort of 'club or country'(football reference) type argument for some people who feel their identify diminished.


The rise of the machines has been in motion for hundreds of years disrupting employment for hundreds of millions, creating a new kind of under class. This is only going to get worst in terms of negative impact on groups unable to change.

Machines like toasters probably did not take anyone out of employment, if anything they created a net positive of work.



We no longer talk about all the lost jobs


== It will get worst before it gets better

What is certain is that the current clash of ideas will make things worst in terms of normal analysis.

== The solution ?


The natural baffles of time, distance, culture, nations and overall disconnectedness have fallen away.

All of us are effected by all of us and vice versa.

This was always the truth, it is just the time component that has changed.

As Kurt Vonnegut showed us Technocracy is not the solution
https://en.wikipedia.org/wiki/Player_Piano_(novel)

Being both part of the problem and solution 